"""Turning text into an Excel column width.

Excel measures column width in units of the widest digit of the workbook's normal
font, and its own formula for fitting text is::

    width = (pixels of text + 5 padding pixels) / max digit width

The per-character advances behind ``pixels of text`` live in ``_font_widths`` and
are generated by ``tools/generate_font_metrics.py``. Where an openly licensed font
exists that matches a proprietary one advance-for-advance, that is what was
measured; the rest were read from the font files on the machine that generated the
table. Either way what is stored is a table of widths, not any part of a font.

A face with no table falls back to the default one, and ``widths_for`` reports
whether that happened so the fallback need not be silent.

Two details are easy to get wrong and both are load-bearing:

* The font of the *text* and the font defining the *unit* are not the same thing.
  A cell in 22pt inside a workbook whose normal font is 11pt needs roughly twice
  the width; using one size for both makes a larger font produce a smaller number.
* Advances are rounded to whole pixels before being added up, because that is how
  the text is laid out. It is also why Calibri 11, whose digit advance is 7.43
  pixels, has a max digit width of 7. Summing the fractions instead puts a column
  of ten digits at 11.33 rather than the 10.71 the unit defines.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Final

from ._font_widths import ALIASES, FONT_WIDTHS

DEFAULT_FONT_NAME: Final = "calibri"

# Excel adds two pixels of padding either side of the text plus one for the
# gridline, and that total is part of its own width formula.
CELL_PADDING_PIXELS: Final = 5

PIXELS_PER_POINT: Final = 96 / 72


def widths_for(font_name: str | None) -> tuple[Mapping[str, float], bool]:
    """Advance widths for ``font_name``, falling back to the default face.

    Returns ``(widths, matched)``. ``matched`` is False when the font is one we
    have no table for, which callers may want to report rather than silently
    measure Arial as if it were Calibri.
    """
    key = (font_name or DEFAULT_FONT_NAME).strip().lower()
    key = ALIASES.get(key, key)
    table = FONT_WIDTHS.get(key)
    if table is None:
        return FONT_WIDTHS[DEFAULT_FONT_NAME], False
    return table, True


def known_fonts() -> list[str]:
    """Every font name that can be measured, aliases included."""
    return sorted(set(FONT_WIDTHS) | set(ALIASES))


def digit_width(widths: Mapping[str, float]) -> float:
    """Em fraction of the widest digit. Excel's width unit is one of these."""
    return max(widths[d] for d in "0123456789")


def text_pixels(text: str, point_size: float, widths: Mapping[str, float]) -> int:
    fallback = digit_width(widths)
    return sum(
        round(widths.get(character, fallback) * point_size * PIXELS_PER_POINT) for character in text
    )


def max_digit_pixels(point_size: float, widths: Mapping[str, float]) -> int:
    return max(1, round(digit_width(widths) * point_size * PIXELS_PER_POINT))


def column_width(
    text: str,
    point_size: float,
    base_point_size: float | None = None,
    font_name: str | None = None,
    base_font_name: str | None = None,
) -> float:
    """Column width that fits ``text``.

    ``point_size``/``font_name`` describe the text being measured.
    ``base_point_size``/``base_font_name`` describe the workbook's normal font,
    which is what the width unit itself is defined in.
    """
    if base_point_size is None:
        base_point_size = point_size
    text_widths, _ = widths_for(font_name)
    base_widths, _ = widths_for(base_font_name if base_font_name is not None else font_name)
    return (text_pixels(text, point_size, text_widths) + CELL_PADDING_PIXELS) / max_digit_pixels(
        base_point_size, base_widths
    )
