"""Turning text into an Excel column width.

Excel measures column width in units of the widest digit of the workbook's normal
font, and its own formula for fitting text is::

    width = (pixels of text + 5 padding pixels) / max digit width

The per-character advances behind ``pixels of text`` live in ``_font_widths`` and
are generated by ``tools/generate_font_metrics.py``. Where an openly licensed font
exists that matches a proprietary one advance-for-advance, that is what was
measured; the rest were read from the font files on the machine that generated the
table. Either way what is stored is a table of widths, not any part of a font.

A face with no table falls back to another, and ``widths_for`` reports whether
that happened so the fallback need not be silent. Which face it falls back to
depends on what is being measured, and the two are not the same: see the note
above ``UNKNOWN_FONT_NAME``.

Two details are easy to get wrong and both are load-bearing:

* The font of the *text* and the font defining the *unit* are not the same thing.
  A cell in 22pt inside a workbook whose normal font is 11pt needs roughly twice
  the width; using one size for both makes a larger font produce a smaller number.
* Advances are rounded to whole pixels before being added up, because that is how
  the text is laid out. It is also why Calibri 11, whose digit advance is 7.43
  pixels, has a max digit width of 7. Summing the fractions instead puts a column
  of ten digits at 11.33 rather than the 10.71 the unit defines.
"""

from __future__ import annotations

from collections.abc import Mapping
from typing import Final

from ._font_widths import ALIASES, FONT_WIDTHS

# Excel's own default, and so the face the width unit is defined in when a workbook
# names none. This is a statement of fact about Excel, not a choice: widening it
# would widen the unit and make every measurement smaller.
DEFAULT_FONT_NAME: Final = "calibri"

# A named face with no table of its own is measured with this one. The widest table
# is used deliberately. The two errors are not equally bad -- a column measured too
# narrow hides what it holds, while one measured too wide only looks untidy -- so an
# unknown face is given the benefit of the doubt. Calibri is the narrowest of the
# ten and under-measures every other one, which makes it the worst choice here even
# though it is the right one above.
UNKNOWN_FONT_NAME: Final = "verdana"

# Excel adds two pixels of padding either side of the text plus one for the
# gridline, and that total is part of its own width formula.
CELL_PADDING_PIXELS: Final = 5

PIXELS_PER_POINT: Final = 96 / 72


def widths_for(
    font_name: str | None, fallback: str = UNKNOWN_FONT_NAME
) -> tuple[Mapping[str, float], bool]:
    """Advance widths for ``font_name``, falling back to ``fallback``.

    Returns ``(widths, matched)``. ``matched`` is False when the font is one we
    have no table for, which callers may want to report rather than silently
    measure Segoe UI as if it were Verdana.

    No name at all is not an unknown face: it means the workbook named none, so
    Excel's default applies and the fallback does not come into it.
    """
    if font_name is None:
        return FONT_WIDTHS[DEFAULT_FONT_NAME], True
    key = font_name.strip().lower()
    key = ALIASES.get(key, key)
    table = FONT_WIDTHS.get(key)
    if table is None:
        return FONT_WIDTHS[fallback], False
    return table, True


def known_fonts() -> list[str]:
    """Every font name that can be measured, aliases included."""
    return sorted(set(FONT_WIDTHS) | set(ALIASES))


def digit_width(widths: Mapping[str, float]) -> float:
    """Em fraction of the widest digit. Excel's width unit is one of these."""
    return max(widths[d] for d in "0123456789")


def text_pixels(text: str, point_size: float, widths: Mapping[str, float]) -> int:
    fallback = digit_width(widths)
    return sum(
        round(widths.get(character, fallback) * point_size * PIXELS_PER_POINT) for character in text
    )


def max_digit_pixels(point_size: float, widths: Mapping[str, float]) -> int:
    return max(1, round(digit_width(widths) * point_size * PIXELS_PER_POINT))


def column_width(
    text: str,
    point_size: float,
    base_point_size: float | None = None,
    font_name: str | None = None,
    base_font_name: str | None = None,
) -> float:
    """Column width that fits ``text``.

    ``point_size``/``font_name`` describe the text being measured.
    ``base_point_size``/``base_font_name`` describe the workbook's normal font,
    which is what the width unit itself is defined in.
    """
    if base_point_size is None:
        base_point_size = point_size
    text_widths, _ = widths_for(font_name)
    # The unit falls back to Excel's default rather than to the wide face. Widening
    # the unit divides by more and hands back a narrower column, which is the
    # opposite of what the wide fallback is for.
    base_widths, _ = widths_for(
        base_font_name if base_font_name is not None else font_name,
        fallback=DEFAULT_FONT_NAME,
    )
    return (text_pixels(text, point_size, text_widths) + CELL_PADDING_PIXELS) / max_digit_pixels(
        base_point_size, base_widths
    )
